packages:
  - apps/*
  - packages/*
  - internal/*
  - scripts/*
catalog:
  "@eslint/js": ^10.0.1
  "@stylistic/stylelint-plugin": ^4.0.1
  "@types/eslint": ^9.6.1
  "@types/node": ^24.10.13
  "@typescript-eslint/eslint-plugin": ^7.18.0
  "@typescript-eslint/parser": ^7.18.0
  "@vitejs/plugin-vue": ^6.0.4
  "@vue/tsconfig": ^0.8.1
  cspell: ^9.6.4
  eslint: ^9.39.3
  eslint-config-turbo: ^2.8.10
  eslint-plugin-perfectionist: ^5.6.0
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-unused-imports: ^4.4.1
  postcss: ^8.5.6
  postcss-html: ^1.8.1
  postcss-scss: ^4.0.9
  prettier: ^3.8.1
  prettier-plugin-tailwindcss: ^0.7.2
  stylelint: ^16.26.1
  stylelint-config-recess-order: ^7.6.1
  stylelint-config-recommended: ^17.0.0
  stylelint-config-recommended-scss: ^16.0.2
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^39.0.1
  stylelint-order: ^7.0.1
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^6.14.0
  turbo: ^2.8.10
  typescript: ~5.9.3
  unbuild: ^2.0.0
  vite: ^7.3.1
  vue: ^3.5.28
  vue-tsc: ^3.2.5
